### ISSUE TITLE
ts2arr not found

### ISSUE THREAD

**Issue by ShellyGB** [fengineering-ch/x13tbx#3]
Hi, 

Excuse me, I'm trying to run x13 on an own timeseries, however it says _Unrecognized function or variable 'ts2arr'_. I couldnt find that function on the folder. What could I do?

**Comment by fengineering-ch** [comment]
ShellyGB, Sorry to hear that.
Could you please provide the full error message? I need to know in which file and line this error occurrs. This information should be provided in the error message. Just paste the full information here, please.

**Comment by fengineering-ch** [comment]
ShellyGB, Sorry to hear that.
Could you please provide the full error message? I need to know in which file and line this error occurrs. This information should be provided in the error message. Just paste the full information here, please.

**Comment by fengineering-ch** [comment]
No further explanation received. I am closing this issue, as it is not reproducible.
